//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Condello_Controllo_CF.calcoloCodiceFiscale {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CodiceFiscaleSoap", Namespace="http://webservices.dotnethell.it/CodiceFiscale")]
    public partial class CodiceFiscale : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CalcolaCodiceFiscaleOperationCompleted;
        
        private System.Threading.SendOrPostCallback CodiceComuneOperationCompleted;
        
        private System.Threading.SendOrPostCallback NomeComuneOperationCompleted;
        
        private System.Threading.SendOrPostCallback ControllaCodiceFiscaleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CodiceFiscale() {
            this.Url = global::Condello_Controllo_CF.Properties.Settings.Default.Condello_Controllo_CF_calcoloCodiceFiscale_CodiceFiscale;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CalcolaCodiceFiscaleCompletedEventHandler CalcolaCodiceFiscaleCompleted;
        
        /// <remarks/>
        public event CodiceComuneCompletedEventHandler CodiceComuneCompleted;
        
        /// <remarks/>
        public event NomeComuneCompletedEventHandler NomeComuneCompleted;
        
        /// <remarks/>
        public event ControllaCodiceFiscaleCompletedEventHandler ControllaCodiceFiscaleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.dotnethell.it/CodiceFiscale/CalcolaCodiceFiscale", RequestNamespace="http://webservices.dotnethell.it/CodiceFiscale", ResponseNamespace="http://webservices.dotnethell.it/CodiceFiscale", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CalcolaCodiceFiscale(string Nome, string Cognome, string ComuneNascita, string DataNascita, string Sesso) {
            object[] results = this.Invoke("CalcolaCodiceFiscale", new object[] {
                        Nome,
                        Cognome,
                        ComuneNascita,
                        DataNascita,
                        Sesso});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CalcolaCodiceFiscaleAsync(string Nome, string Cognome, string ComuneNascita, string DataNascita, string Sesso) {
            this.CalcolaCodiceFiscaleAsync(Nome, Cognome, ComuneNascita, DataNascita, Sesso, null);
        }
        
        /// <remarks/>
        public void CalcolaCodiceFiscaleAsync(string Nome, string Cognome, string ComuneNascita, string DataNascita, string Sesso, object userState) {
            if ((this.CalcolaCodiceFiscaleOperationCompleted == null)) {
                this.CalcolaCodiceFiscaleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalcolaCodiceFiscaleOperationCompleted);
            }
            this.InvokeAsync("CalcolaCodiceFiscale", new object[] {
                        Nome,
                        Cognome,
                        ComuneNascita,
                        DataNascita,
                        Sesso}, this.CalcolaCodiceFiscaleOperationCompleted, userState);
        }
        
        private void OnCalcolaCodiceFiscaleOperationCompleted(object arg) {
            if ((this.CalcolaCodiceFiscaleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalcolaCodiceFiscaleCompleted(this, new CalcolaCodiceFiscaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.dotnethell.it/CodiceFiscale/CodiceComune", RequestNamespace="http://webservices.dotnethell.it/CodiceFiscale", ResponseNamespace="http://webservices.dotnethell.it/CodiceFiscale", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CodiceComune(string NomeComune) {
            object[] results = this.Invoke("CodiceComune", new object[] {
                        NomeComune});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CodiceComuneAsync(string NomeComune) {
            this.CodiceComuneAsync(NomeComune, null);
        }
        
        /// <remarks/>
        public void CodiceComuneAsync(string NomeComune, object userState) {
            if ((this.CodiceComuneOperationCompleted == null)) {
                this.CodiceComuneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCodiceComuneOperationCompleted);
            }
            this.InvokeAsync("CodiceComune", new object[] {
                        NomeComune}, this.CodiceComuneOperationCompleted, userState);
        }
        
        private void OnCodiceComuneOperationCompleted(object arg) {
            if ((this.CodiceComuneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CodiceComuneCompleted(this, new CodiceComuneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.dotnethell.it/CodiceFiscale/NomeComune", RequestNamespace="http://webservices.dotnethell.it/CodiceFiscale", ResponseNamespace="http://webservices.dotnethell.it/CodiceFiscale", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NomeComune([System.Xml.Serialization.XmlElementAttribute("CodiceComune")] string CodiceComune1) {
            object[] results = this.Invoke("NomeComune", new object[] {
                        CodiceComune1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NomeComuneAsync(string CodiceComune1) {
            this.NomeComuneAsync(CodiceComune1, null);
        }
        
        /// <remarks/>
        public void NomeComuneAsync(string CodiceComune1, object userState) {
            if ((this.NomeComuneOperationCompleted == null)) {
                this.NomeComuneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNomeComuneOperationCompleted);
            }
            this.InvokeAsync("NomeComune", new object[] {
                        CodiceComune1}, this.NomeComuneOperationCompleted, userState);
        }
        
        private void OnNomeComuneOperationCompleted(object arg) {
            if ((this.NomeComuneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NomeComuneCompleted(this, new NomeComuneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.dotnethell.it/CodiceFiscale/ControllaCodiceFiscale", RequestNamespace="http://webservices.dotnethell.it/CodiceFiscale", ResponseNamespace="http://webservices.dotnethell.it/CodiceFiscale", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ControllaCodiceFiscale(string CodiceFiscale) {
            object[] results = this.Invoke("ControllaCodiceFiscale", new object[] {
                        CodiceFiscale});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ControllaCodiceFiscaleAsync(string CodiceFiscale) {
            this.ControllaCodiceFiscaleAsync(CodiceFiscale, null);
        }
        
        /// <remarks/>
        public void ControllaCodiceFiscaleAsync(string CodiceFiscale, object userState) {
            if ((this.ControllaCodiceFiscaleOperationCompleted == null)) {
                this.ControllaCodiceFiscaleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnControllaCodiceFiscaleOperationCompleted);
            }
            this.InvokeAsync("ControllaCodiceFiscale", new object[] {
                        CodiceFiscale}, this.ControllaCodiceFiscaleOperationCompleted, userState);
        }
        
        private void OnControllaCodiceFiscaleOperationCompleted(object arg) {
            if ((this.ControllaCodiceFiscaleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ControllaCodiceFiscaleCompleted(this, new ControllaCodiceFiscaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CalcolaCodiceFiscaleCompletedEventHandler(object sender, CalcolaCodiceFiscaleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalcolaCodiceFiscaleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalcolaCodiceFiscaleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CodiceComuneCompletedEventHandler(object sender, CodiceComuneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CodiceComuneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CodiceComuneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void NomeComuneCompletedEventHandler(object sender, NomeComuneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NomeComuneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NomeComuneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ControllaCodiceFiscaleCompletedEventHandler(object sender, ControllaCodiceFiscaleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ControllaCodiceFiscaleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ControllaCodiceFiscaleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591