//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calcolatrice_wpf.calcolatrice_servizio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="calcolatrice_servizio.calcolatrice_servizioSoap")]
    public interface calcolatrice_servizioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SommaNumeri", ReplyAction="*")]
        double SommaNumeri(double Primo, double Secondo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SommaNumeri", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SommaNumeriAsync(double Primo, double Secondo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SottraiNumeri", ReplyAction="*")]
        double SottraiNumeri(double Primo, double Secondo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SottraiNumeri", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SottraiNumeriAsync(double Primo, double Secondo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoltiplicaNumeri", ReplyAction="*")]
        double MoltiplicaNumeri(double Primo, double Secondo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoltiplicaNumeri", ReplyAction="*")]
        System.Threading.Tasks.Task<double> MoltiplicaNumeriAsync(double Primo, double Secondo);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento DividiNumeriResult dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DividiNumeri", ReplyAction="*")]
        calcolatrice_wpf.calcolatrice_servizio.DividiNumeriResponse DividiNumeri(calcolatrice_wpf.calcolatrice_servizio.DividiNumeriRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DividiNumeri", ReplyAction="*")]
        System.Threading.Tasks.Task<calcolatrice_wpf.calcolatrice_servizio.DividiNumeriResponse> DividiNumeriAsync(calcolatrice_wpf.calcolatrice_servizio.DividiNumeriRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DividiNumeriRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DividiNumeri", Namespace="http://tempuri.org/", Order=0)]
        public calcolatrice_wpf.calcolatrice_servizio.DividiNumeriRequestBody Body;
        
        public DividiNumeriRequest() {
        }
        
        public DividiNumeriRequest(calcolatrice_wpf.calcolatrice_servizio.DividiNumeriRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DividiNumeriRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double primo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double secondo;
        
        public DividiNumeriRequestBody() {
        }
        
        public DividiNumeriRequestBody(double primo, double secondo) {
            this.primo = primo;
            this.secondo = secondo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DividiNumeriResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DividiNumeriResponse", Namespace="http://tempuri.org/", Order=0)]
        public calcolatrice_wpf.calcolatrice_servizio.DividiNumeriResponseBody Body;
        
        public DividiNumeriResponse() {
        }
        
        public DividiNumeriResponse(calcolatrice_wpf.calcolatrice_servizio.DividiNumeriResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DividiNumeriResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DividiNumeriResult;
        
        public DividiNumeriResponseBody() {
        }
        
        public DividiNumeriResponseBody(string DividiNumeriResult) {
            this.DividiNumeriResult = DividiNumeriResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface calcolatrice_servizioSoapChannel : calcolatrice_wpf.calcolatrice_servizio.calcolatrice_servizioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class calcolatrice_servizioSoapClient : System.ServiceModel.ClientBase<calcolatrice_wpf.calcolatrice_servizio.calcolatrice_servizioSoap>, calcolatrice_wpf.calcolatrice_servizio.calcolatrice_servizioSoap {
        
        public calcolatrice_servizioSoapClient() {
        }
        
        public calcolatrice_servizioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public calcolatrice_servizioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calcolatrice_servizioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calcolatrice_servizioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double SommaNumeri(double Primo, double Secondo) {
            return base.Channel.SommaNumeri(Primo, Secondo);
        }
        
        public System.Threading.Tasks.Task<double> SommaNumeriAsync(double Primo, double Secondo) {
            return base.Channel.SommaNumeriAsync(Primo, Secondo);
        }
        
        public double SottraiNumeri(double Primo, double Secondo) {
            return base.Channel.SottraiNumeri(Primo, Secondo);
        }
        
        public System.Threading.Tasks.Task<double> SottraiNumeriAsync(double Primo, double Secondo) {
            return base.Channel.SottraiNumeriAsync(Primo, Secondo);
        }
        
        public double MoltiplicaNumeri(double Primo, double Secondo) {
            return base.Channel.MoltiplicaNumeri(Primo, Secondo);
        }
        
        public System.Threading.Tasks.Task<double> MoltiplicaNumeriAsync(double Primo, double Secondo) {
            return base.Channel.MoltiplicaNumeriAsync(Primo, Secondo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        calcolatrice_wpf.calcolatrice_servizio.DividiNumeriResponse calcolatrice_wpf.calcolatrice_servizio.calcolatrice_servizioSoap.DividiNumeri(calcolatrice_wpf.calcolatrice_servizio.DividiNumeriRequest request) {
            return base.Channel.DividiNumeri(request);
        }
        
        public string DividiNumeri(double primo, double secondo) {
            calcolatrice_wpf.calcolatrice_servizio.DividiNumeriRequest inValue = new calcolatrice_wpf.calcolatrice_servizio.DividiNumeriRequest();
            inValue.Body = new calcolatrice_wpf.calcolatrice_servizio.DividiNumeriRequestBody();
            inValue.Body.primo = primo;
            inValue.Body.secondo = secondo;
            calcolatrice_wpf.calcolatrice_servizio.DividiNumeriResponse retVal = ((calcolatrice_wpf.calcolatrice_servizio.calcolatrice_servizioSoap)(this)).DividiNumeri(inValue);
            return retVal.Body.DividiNumeriResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<calcolatrice_wpf.calcolatrice_servizio.DividiNumeriResponse> calcolatrice_wpf.calcolatrice_servizio.calcolatrice_servizioSoap.DividiNumeriAsync(calcolatrice_wpf.calcolatrice_servizio.DividiNumeriRequest request) {
            return base.Channel.DividiNumeriAsync(request);
        }
        
        public System.Threading.Tasks.Task<calcolatrice_wpf.calcolatrice_servizio.DividiNumeriResponse> DividiNumeriAsync(double primo, double secondo) {
            calcolatrice_wpf.calcolatrice_servizio.DividiNumeriRequest inValue = new calcolatrice_wpf.calcolatrice_servizio.DividiNumeriRequest();
            inValue.Body = new calcolatrice_wpf.calcolatrice_servizio.DividiNumeriRequestBody();
            inValue.Body.primo = primo;
            inValue.Body.secondo = secondo;
            return ((calcolatrice_wpf.calcolatrice_servizio.calcolatrice_servizioSoap)(this)).DividiNumeriAsync(inValue);
        }
    }
}
